version: '2.4'

services:
  db:
    image: mariadb
    restart: unless-stopped
    
    mem_limit: 300m
    
    environment:
      - MYSQL_ROOT_PASSWORD=AaFpqD6uCY5F
      - TZ=Europe/Zurich
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/db/db_schema.dev.sql:/docker-entrypoint-initdb.d/db_schema.sql
    networks: 
      ooNet:
        ipv4_address: 172.33.0.2

  s3:
    image: minio/minio
    restart: unless-stopped
    volumes:
      - ./data/s3:/data
    environment:
      - MINIO_ACCESS_KEY=openolitor
      - MINIO_SECRET_KEY=uGuRR53g4uR6c8R4yCxfNwFF
    command: server /data
    ## depending on network setup
    ports:
      - "9050:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://s3:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      ooNet:
        ipv4_address: 172.33.0.3

  server:
    image: openolitor/openolitor-server:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
    volumes:
    # server settings
      - ./config/server/openolitor-server.dev.conf:/etc/openolitor-server/application.conf
      - ./config/server/openolitor-server-logback.xml:/etc/openolitor-server/logback.xml
      - ./log/server/:/var/log/openolitor-server/
    depends_on:
      - db
      - s3
    ports:
      - "9003:9003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:9003/csa1/open/projekt"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      ooNet:
        ipv4_address: 172.33.0.4

  client-admin:
    image: openolitor/openolitor-client-admin:latest
    ports:
      - "9100:80"
    restart: unless-stopped
    volumes:
      - ./config/client/admin/config.dev.js:/usr/share/nginx/html/environments/config.js
    ## depending on network setup
    networks: 
      ooNet:
        ipv4_address: 172.33.0.5

  client-kundenportal:
    image: openolitor/openolitor-client-kundenportal:latest
    ports:
      - "9110:80"
    restart: unless-stopped
    volumes:
      - ./config/client/kundenportal/config.dev.js:/usr/share/nginx/html/environments/config.js
    networks: 
      ooNet:
        ipv4_address: 172.33.0.6

  nginx:
    image: nginx:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
    ports:
      - "80:9000"
      - "13423:13423"
    volumes:
      - ./config/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./config/nginx/smtp-proxy-htpasswd:/etc/nginx/htpasswd
    depends_on:
      - client-admin
      - client-kundenportal
      - server
    networks: 
      ooNet:
        ipv4_address: 172.33.0.7

  pdf-tool:
    image: eugenmayer/jodconverter:rest
    restart: unless-stopped
    ports:
      - "9040:8080"
    networks: 
      ooNet:
        ipv4_address: 172.33.0.8

  smtp-server:
    image: bytemark/smtp
    environment:
      MAILNAME: your-smtp.server.zzz
    restart: always

  
  smtp-proxy:
    image: mailhog/mailhog
    environment:
      - TZ=Europe/Zurich
    ports:
      - "1025:1025"
      - "8025:8025"
    networks: 
      ooNet:
        ipv4_address: 172.33.0.9
  

networks:
  ooNet:
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1