version: '2.4'

services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=ofCourseThisIsTrueForTheRootPasswordToo
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    ports:
      - "3306:3306"
  s3:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    restart: unless-stopped
    volumes:
      - ./data/s3:/data
    environment:
      - MINIO_ACCESS_KEY=miniouserallcsa
      - MINIO_SECRET_KEY=thedefaultminiosecretneedstobechanged
    command: server /data
    ports:
      - "9050:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  server:
    image: openolitor/openolitor-server
    restart: unless-stopped
    volumes:
    # server settings
      - ./config/server/openolitor-server.conf:/etc/openolitor-server/application.conf
      - ./config/server/openolitor-server-logback.xml:/etc/openolitor-server/logback.xml
      - ./log/server/akka.log:/var/log/openolitor-server/akka.log
    depends_on:
    - db
    - s3
    ports:
    - "9003:9003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:9003/m1/open/projekt"]
      interval: 30s
      timeout: 20s
      retries: 3

  client-admin:
    image: openolitor/openolitor-client-admin
    restart: unless-stopped
    volumes:
      - ./config/client/admin/config.js:/usr/share/nginx/html/environments/config.js

  client-kundenportal:
    image: openolitor/openolitor-client-kundenportal
    restart: unless-stopped
    volumes:
      - ./config/client/kundenportal/config.js:/usr/share/nginx/html/environments/config.js

  nginx:
    image: nginx:latest
    ports:
      - "8080:9000"
    volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client-admin
      - client-kundenportal
      - server

  pdf-tool:
    image: eugenmayer/jodconverter:rest
    ports:
      - "9040:8080"

  smtp-proxy:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
